apiVersion: v1
kind: Namespace
metadata:
  annotations:
    fleet.gke.io/fns-resource-link: //gkehub.googleapis.com/projects/877381117738/locations/global/namespaces/ns16
  labels:
    fleet.gke.io/actuation-active: "false"
    kubernetes.io/metadata.name: ns17
  name: ns17

