apiVersion: v1
kind: Namespace
metadata:
  annotations:
    creator: fleet
    fleet.gke.io/fns-resource-link: //gkehub.googleapis.com/projects/877381117738/locations/global/namespaces/ns1
  labels:
    kubernetes.io/metadata.name: ns2
    test-data: "true"
  name: ns2

